### ISSUE TITLE
US 1:  Retrieve and List Flights

### ISSUE THREAD

**Issue by NicoleHoerner** [NicoleHoerner/Capstone-Project-Flight-Tracking#1]
## Value Proposition

**As a** pilot, traveler or just as an aviation enthusiast
**I want to** see a list of specific flights I'm performing or some how are of my interest during a month (or other period of time)
**so that** I can easily review and manage my flight data.
​

## Description

​![image](https://github.com/NicoleHoerner/Capstone-Project-Flight-Tracking/assets/128461153/05b56d41-2572-4c0c-9751-a1c8cbf088bb)
## Acceptance Criteria

- [ ] Upon landing on the dashboard/homepage, the user sees a section with a list of flights.
- [ ] The list displays flight details (e.g. flight number, departure/arrival locations or other data depending on the API and will be adjusted in future user stories)
- [ ] The flight list is populated with data fetched from a flight/aviation API.
      ​

## Tasks

- [ ] Open a new branch
- [ ] Prepare a list of desired flights
- [ ] Get API access
- [ ] Implement API integration to fetch flight data. (Create a new endpoint in the Pages folder under api and in the frontend at this point on the homepage make the list displayed)

## Complexity

M
