### ISSUE TITLE
US7:

### ISSUE THREAD

**Issue by NicoleHoerner** [NicoleHoerner/Capstone-Project-Flight-Tracking#12]
## Value Proposition

**As a** pilot, traveler or just as an aviation enthusiast
**I want to** see one or more flights displayed on the dashboard that are scheduled for today 
**so that** I can stay informed about flights for today directly without searching.
​

## Description

![image](https://github.com/NicoleHoerner/Capstone-Project-Flight-Tracking/assets/128461153/76c7b540-1e18-4e69-9622-b6eab4b19dfe)
​

## Acceptance Criteria

- [ ] The dashboard displays one or more flights with today's date, if available, according the scheduled flights form the flight list.
- [ ] If there are no flights with today's date in the flight list, no flights should be displayed on the dashboard.
- [ ] The flight information displayed on the dashboard should be retrieved from API.
- [ ] The heading of the dashboard is according to the app.
      ​

## Tasks

- [ ] create a new branch
- [ ] Create a component to display flight information on the dashboard.
- [ ] Implement logic to filter and display flights based on today's date.
- [ ] Ensure that the flight information updates in real-time, that displayed flights' additional information is fetched from API.
- [ ] Change and style heading of dashboard page.
- [ ] (I might also incorporate some testing at this stage)
      ​

## Complexity

L
