### ISSUE TITLE
US8: design and layout adjustments

### ISSUE THREAD

**Issue by NicoleHoerner** [NicoleHoerner/Capstone-Project-Flight-Tracking#14]
## Value Proposition

**As a** Web developer student,
**I want to** have a visually appealing and consistent app design 
**so that**one can enjoy a pleasant and informative user experience while using the app.
​
## Description
- (no wireframe)
- in case it`s possible: option to include extra features: a map and date/time on the dashboard
​

## Acceptance Criteria

- [ ] Throughout the app consistent and visually pleasing layout, style, and design is seen, besides maintaining functional aspects
- [ ] The About page text should provide relevant information about the app and its purpose.
      ​

## Tasks

- [ ] Open new branch
- [ ] Adjust About page, populate the About page with informative and engaging text that describes the app's purpose
- [ ] Make layout, styling changes/adjustments (final color palette)
- [ ] Review app, make UI/UX adjustments
- [ ] optional (add map, date/time on dashboard) If the map feature is enabled, integrate a map component that displays aviation-related information on the dashboard, as well as the date/time display      ​

## Complexity

M-L
