### ISSUE TITLE
US2: Navigation Menu and "About" Page 

### ISSUE THREAD

**Issue by NicoleHoerner** [NicoleHoerner/Capstone-Project-Flight-Tracking#3]
## Value Proposition

**As a** pilot, traveler or just as an aviation enthusiast
**I want to** navigate between the dashboard and an "About" page,
**so that** I can learn more about the app and its purpose.
​

## Description

![image](https://github.com/NicoleHoerner/Capstone-Project-Flight-Tracking/assets/128461153/3bc0686f-7fc3-4b20-8b07-897b972546ee)

​

## Acceptance Criteria

- [ ] A navigation menu displays links to the dashboard/home and the "About" page.
- [ ] Clicking on the "About" link takes the user to a separate "About" page with content.
      ​

## Tasks

- [ ] Create a new branch
- [ ] Create a Navigation component in the components folder.
- [ ] Create the About Page in the pages directory.
- [ ] Import the Navigation component into the About Page component.
- [ ] Add heading and a brief description of the app's purpose. (right now just a placeholder for text)
- [ ] Add the Navigation component to the Dashboard component.
      ​

## Complexity

M

**Comment by NicoleHoerner** [comment]
Updated wireframe!
