### ISSUE TITLE
US3: add/enhance Layout & create "Flight List" Page

### ISSUE THREAD

**Issue by NicoleHoerner** [NicoleHoerner/Capstone-Project-Flight-Tracking#4]
## Value Proposition

**As a** pilot, traveler or just as an aviation enthusiast
**I want** the app's layout to be organized and consistent across all pages, and I also want to explore a dedicated "Flight List" page
**so that** a seamless design layout experience and informative details about scheduled flights are ensured.
​

## Description

![image](https://github.com/NicoleHoerner/Capstone-Project-Flight-Tracking/assets/128461153/68659fdd-98f6-4246-87d9-cc73d5f6e06d)
​

## Acceptance Criteria

- [ ] A layout that is consistent across all pages is implemented and encapsulates common elements, e.g. navigation menu.
- [ ] The layout maintains its structure and styling across different pages.
- [ ] A new page with scheduled flights* can be navigated to.
- [ ] Example flight/flights is/are displayed with flight number and scheduled date.
      ​

## Tasks

- [ ] Create a new branch
- [ ] Create a layout component
- [ ] Define the common layout structure
- [ ] Ensure the layout is consistently applied to all pages / import layout to app
- [ ] Create the Flight List Page in the pages directory.
- [ ] Display flight details such as flight number and scheduled flight
      ​

## Complexity

M

**Comment by NicoleHoerner** [comment]
*please note: at this stage there is just an example list of flights displayed. This US is just for the purpose to navigate to that new page and that the user can see something.
adding, editing, deleting flights will be implemented later

**Comment by MiketheBite** [comment]
Looks good to me! 😉
