### ISSUE TITLE
US4: add additional flight feature

### ISSUE THREAD

**Issue by NicoleHoerner** [NicoleHoerner/Capstone-Project-Flight-Tracking#6]
## Value Proposition

**As a** pilot, traveler or just as an aviation enthusiast
**I want to** be able to add further flights to my scheduled flights list
**so that** I can expand the list with additional flights of interest if necessary.
​

## Description

![image](https://github.com/NicoleHoerner/Capstone-Project-Flight-Tracking/assets/128461153/8866f2a5-ccdb-40e9-ba92-dd8571c3fb84)​

## Acceptance Criteria

- [ ] On the Flight List page, there should be an "Add Flight" button displayed
- [ ] Clicking the "Add Flight" button, a new page opens with a form for entering flight details.
- [ ] After filling out the input fields, data can be submitted.
- [ ] The new flight's data should be listed in on the flight list's page
      ​

## Tasks

- [ ] Create a new branch
- [ ] Create "Add Flight" Button
- [ ] Design form for adding new flight
- [ ] Implement flight form validation
- [ ] Handle form submission
- [ ] Update flight list display
      ​

## Complexity

M/L
