### ISSUE TITLE
US5: edit/update flight detail 

### ISSUE THREAD

**Issue by NicoleHoerner** [NicoleHoerner/Capstone-Project-Flight-Tracking#7]
## Value Proposition

**As a** pilot, traveler or just as an aviation enthusiast
**I want to** the ability to edit the details of a listed flight
**so that** I can make corrections or updates when needed.
​

## Description

![image](https://github.com/NicoleHoerner/Capstone-Project-Flight-Tracking/assets/128461153/761fb4c7-5325-4c7a-ba40-ea7b2f52375b)

​

## Acceptance Criteria

- [ ] On the Flight List page, there should be an "Edit" icon or button displayed next to each listed flight.
- [ ] When clicking the "Edit" icon/button for a specific flight, a new page or modal should open, allowing to edit/update the flight's details.
- [ ] Changes to any field of the flight details should be possible.
- [ ] Changes can be saved.
- [ ] If no changes are made, there should be the option to go back to the Flight List page without saving any modifications.

## Tasks

- [ ] Create new branch
- [ ] Create and implement an "Edit" icon or button next to each listed flight on the Flight List page.
- [ ] Design Flight Edit Form (create a new page or modal for editing flight details/input fields pre-filled with the selected flight's data)
- [ ] Add a "Save Changes" button to the flight edit form.
- [ ] Implement functionality to save the changes made to flight details (updating Flight List Display)
- [ ] Include a "Cancel" or "Go Back" button in the edit form to allow users to discard any changes and return to the Flight List page.
      ​

## Complexity

M/L
