### ISSUE TITLE
US6: Delete Flight

### ISSUE THREAD

**Issue by NicoleHoerner** [NicoleHoerner/Capstone-Project-Flight-Tracking#8]
## Value Proposition

**As a** pilot, traveler or just as an aviation enthusiast
**I want to** to be able to delete a listed flight
**so that** I can remove flights that I no longer wish to track.
​

## Description

![image](https://github.com/NicoleHoerner/Capstone-Project-Flight-Tracking/assets/128461153/800559cf-fb8a-433b-9a3a-c2b78e6edae4)

​

## Acceptance Criteria

- [ ] On the Flight List page, there should be a "Delete" icon or button displayed next to each listed flight.
- [ ] When clicking the "Delete" icon/button for a specific flight, a confirmation message should appear, asking to confirm the deletion.
- [ ] If deletion is not desired, there should be the option to abort the operation (e.g. "cancel" button)
- [ ] After confirming the deletion, the flight should be removed from the Flight List page.

## Tasks

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, testing
- [ ] ...
      ​

## Complexity

M (T-Shirt Sizes XS to XL)

**Comment by milodevhh** [comment]
Hey Nicole, looks good too me, I like your first styling. Have fun with that, US!
